# Generated by Django 5.0.6 on 2024-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookid", models.IntegerField()),
                ("booktitle", models.CharField(max_length=300)),
                ("bookauthors", models.CharField(max_length=800)),
                ("bookrating", models.IntegerField()),
                ("bookisbn", models.CharField(max_length=10)),
                ("bookisbn13", models.IntegerField()),
                ("book_language_code", models.CharField(max_length=5)),
                ("bookpages", models.IntegerField()),
                ("book_rating_counts", models.IntegerField()),
                ("book_text_reviews_count", models.IntegerField()),
                ("book_publication_date", models.DateField()),
                ("book_publisher", models.CharField(max_length=100)),
            ],
        ),
    ]
